[project]
name = "nman"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fritzconnection>=1.15.0",
    "rich-argparse>=1.7.2",
]
